version: '3'
services:

  postgres:
    image: postgres:15
    hostname: postgres
    ports:
      - 5432:5432
    env_file:
      - ./../db.conf
    volumes:
      - db-data2:/var/lib/postgresql/data

volumes:
  db-data2:
